### ISSUE TITLE
Custom API

### ISSUE THREAD

**Issue by BasToTheMax** [mediarayek-me/smmbooster#1]
Are there any api docs I need to create a custom api provider

**Comment by mediarayek-me** [comment]
Hi @BasToTheMax,
unfortunately, api docs not available

**Comment by BasToTheMax** [comment]
Why not?

**Comment by mediarayek-me** [comment]
we don't create api provider, we just use api providers that already exist to sell their services, this is the idea of the script.
this script is compatible with:
-MOMO panel
-VINA SMM
-HQ SmartPanel
and you can add others if you want, but you need to adjust parameters.
