### ISSUE TITLE
So many redirects

### ISSUE THREAD

**Issue by CreedoW** [mediarayek-me/smmbooster#2]
https://cdn.mwah.ro/i/GVLMS.png any fix for that thing?

**Comment by mediarayek-me** [comment]
Hi @CreedoW, can you show me page link ?

**Comment by CreedoW** [comment]
> Hi @CreedoW, can you show me page link ?

https://smm.mwah.ro/404.html

**Comment by mediarayek-me** [comment]
Hi, @CreedoW  please check if you follow the installation steps correctly.
