### ISSUE TITLE
script testing

### ISSUE THREAD

**Issue by PowerChaos** [mediarayek-me/smmbooster#3]
hi,
i just want to test this script ( because some one asked about it  ) 
and it is not possible to install

lets start with the beginning
first of all the index file is complete wrong
`require __DIR__.'/../vendor/autoload.php';`
this points to /home/user/site/../vendor....
so fix is by removing those 2 dots ( easy done ) 

now the biggest problem you probably already noticed
There is no vendor folder to start with so it can not include it and it fails

is this script a stand alone version or just a expansion that need to overwrite a other version ?
as there are so many things missing

Greetings from PowerChaos

**Comment by mediarayek-me** [comment]
Hi, @PowerChaos I update the installation wizard, you can clone the repo and try again by following the installation steps in readme file. 
tell me if you face other issues.

**Comment by PowerChaos** [comment]
Thank you
still got the same issue's as first one is never fixed

`2022-02-14 00:16:23.907236 [NOTICE] [8129] [xxxxxx:8073:HTTP2-1#3ddata.be] [STDERR] PHP Fatal error:  require(): Failed opening required '/home/xxxxxx/public_html/public/../vendor/autoload.php'`

but lets provide more info then this to give a idea what i use to test

i run a litespeed server as you see above my , that means i need to rewrite the public folder to his original location , as it is not the root folder 
`RewriteEngine On 
RewriteRule ^$ public/index.php [L]
RewriteRule ^((?!public/).*)$ public/$1 [L,NC]`
laravel works with a public directory for some reason.

i do not use composer , so that also means that any depency's that get loaded by composer are not avaible
why i do not use composer ? because i do not want to install it using a SSH connection and it is on a shared server.

you could just  bundle the vendor files or all needed files so there is no need for composer
also composer can break your build as it pulls the latest files , so if something critical changes then it is broken. ( or if api fails to pull needed resources ) 

Thank you
Greetings from PowerChaos

**Comment by mediarayek-me** [comment]
Hi again @PowerChaos,
you know that before you upload the files to your server you should run
`composer install`
and after this command run
`npm install`

tow folders will be auto generated **vendor** & **node_modules**

if you are in localhost just run
`php artisan serve`
to run the script in your local serve

**Comment by PowerChaos** [comment]
Thank you @mediarayek-me 
but why do i need to use composer ?
most webhosts does not even allow composer to run for a reason ( because it need SSH access... ) 
so if you local testing the script, just pack those **vendor & node_modules** folder also on github
then there is no need to install/run composer
it is not that they contain username/passwords or other sensitive information ?

and then you are also sure it got the correct files, composer does not always work
specially not if you start to use out of date programs

Thank you
Greetings from PowerChaos

**Comment by mediarayek-me** [comment]
Hi, @PowerChaos 
 we do not push **vendor** & **node_modules** to github , you can generate them in your local machine  using
`composer install && npm install`
before you upload project files to your live hosting

please check this for better understanding
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
https://www.positronx.io/should-i-commit-the-node_modules-folder-to-git/
