### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by doanbactam** [mediarayek-me/smmbooster#4]
can't install due to wrong path, you can check again and try to install on another hosting to understand what i'm saying

**Comment by mediarayek-me** [comment]
Hi @doanbactam, 
did you run 
`composer install` 
and
`npm install`

before upload files to your server?

**Comment by doanbactam** [comment]
i have done it but that makes the framework break and can't load js files
![Screenshot 2022-02-15 094543](https://user-images.githubusercontent.com/24356000/153987688-07b0d7d3-36f8-4118-b67e-87a1e0afdd31.png)

**Comment by mediarayek-me** [comment]
Hi @doanbactam , try to clear browser cache and try `npm install` to install node modules.
also check your browser console to show more informations.

**Comment by doanbactam** [comment]
![Screenshot 2022-02-16 103844](https://user-images.githubusercontent.com/24356000/154191836-35db3313-4c7b-4750-b13e-5dc5916d7751.png)
this is the problem that led to it when i did all the installation steps

**Comment by mediarayek-me** [comment]
did you create a new database before installing the script ?
this screen shows that your database name is  **root**,
**root** is your database username not your database name, please try to create a new database and be careful when you fill out requested informations.
